name: Fluid

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux-x64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: download deps
      run: sudo apt-get update && sudo apt-get install -y libpango1.0-dev libx11-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev libxfixes-dev libpng-dev libgl1-mesa-dev libglu1-mesa-dev
    - name: download fltk
      run: git clone https://github.com/fltk/fltk --depth=1
    - name: Configure
      run: cd fltk && cmake -Bbin -DCMAKE_BUILD_TYPE=Release -GNinja -DFLTK_BUILD_TEST=OFF -DOPTION_USE_PANGO=ON -DOPTION_USE_CAIRO=ON -DFLTK_BUILD_EXAMPLES=OFF -DOPTION_BUILD_HTML_DOCUMENTATION=OFF -DOPTION_BUILD_PDF_DOCUMENTATION=OFF
    - name: Build
      run: cd fltk && cmake --build bin --config Release
    - name: Strip
      run: strip fltk/bin/bin/fluid
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: fluid-linux-x64
        path: fltk/bin/bin/fluid
  macos-x64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: download fltk
      run: git clone https://github.com/fltk/fltk --depth=1
    - name: Configure
      run: cd fltk && cmake -Bbin -DCMAKE_BUILD_TYPE=Release -GNinja -DFLTK_BUILD_TEST=OFF -DFLTK_BUILD_EXAMPLES=OFF -DOPTION_BUILD_HTML_DOCUMENTATION=OFF -DOPTION_BUILD_PDF_DOCUMENTATION=OFF
    - name: Build
      run: cd fltk && cmake --build bin --config Release
    - name: Strip
      run: strip fltk/bin/bin/fluid
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: fluid-macos-x64
        path: fltk/bin/bin/fluid
  windows-x64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: download fltk
      run: git clone https://github.com/fltk/fltk --depth=1
    - name: Configure
      run: cd fltk && cmake -Bbin -DCMAKE_BUILD_TYPE=Release -DFLTK_BUILD_TEST=OFF -DFLTK_BUILD_EXAMPLES=OFF -DOPTION_BUILD_HTML_DOCUMENTATION=OFF -DOPTION_BUILD_PDF_DOCUMENTATION=OFF
    - name: Build
      run: cd fltk && cmake --build bin --config Release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: fluid-windows-x64
        path: fltk\bin\
